<?php

namespace app\controllers;

use app\models\LoginForm;
use app\models\SignupForm;
use Yii;
use yii\base\Exception;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\Cors;
use yii\rest\Controller;

class AuthController extends Controller
{
    public $enableCsrfValidation = false;

    /**
     * @throws Exception
     */
    public function actionSignup(): array
    {
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->bodyParams, '') && $model->validate()) {
            $user = $model->signup();

            if ($user) {
                return [
                    'status' => 'success',
                    'user_id' => $user->id,
                    'auth_key' => $user->authKey
                ];
            }
        }
        return ['errors' => $model->errors];
    }

    public function actionLogin(): bool|array
    {
        $model = new LoginForm();

        if ($model->load(Yii::$app->request->bodyParams, '') && $model->validate()) {
            return $model->getUser();
        }
        return ['errors' => $model->errors];
    }

    public function behaviors(): array
    {
        $behaviors = parent::behaviors();

        $behaviors['corsFilter'] = [
            'class' => Cors::class,
            'cors' => [
                'Origin' => ['*'],
                'Access-Control-Request-Method' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
                'Access-Control-Allow-Credentials' => true,
            ]
        ];

        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::class
        ];

        //các actions Signup và Login phải dành cho KHÁCH (Guest)
        $behaviors['authenticator']['except'] = ['signup', 'login'];

        return $behaviors; // TODO: Change the autogenerated stub
    }
}